-- MySQL schema for household_management
CREATE DATABASE IF NOT EXISTS household_management
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE household_management;

-- Địa lý
CREATE TABLE THANHPHO (
    MATHANHPHO INT AUTO_INCREMENT PRIMARY KEY,
    TENTHANHPHO VARCHAR(100)
) ENGINE=InnoDB;

CREATE TABLE QUANHUYEN (
    MAQUANHUYEN INT AUTO_INCREMENT PRIMARY KEY,
    TENQUANHUYEN VARCHAR(100),
    MATHANHPHO INT,
    CONSTRAINT FK_QUANHUYEN_THANHPHO FOREIGN KEY (MATHANHPHO) REFERENCES THANHPHO(MATHANHPHO)
) ENGINE=InnoDB;

CREATE TABLE XAPHUONG (
    MAXAPHUONG INT AUTO_INCREMENT PRIMARY KEY,
    TENXAPHUONG VARCHAR(100),
    MAQUANHUYEN INT,
    CONSTRAINT FK_XAPHUONG_QUANHUYEN FOREIGN KEY (MAQUANHUYEN) REFERENCES QUANHUYEN(MAQUANHUYEN)
) ENGINE=InnoDB;

-- Hộ khẩu
CREATE TABLE HOKHAU (
    SOHOKHAU INT AUTO_INCREMENT PRIMARY KEY,
    DIACHI TEXT,
    MAXAPHUONG INT,
    NGAYCAP DATETIME,
    GHICHU TEXT,
    CONSTRAINT FK_HOKHAU_XAPHUONG FOREIGN KEY (MAXAPHUONG) REFERENCES XAPHUONG(MAXAPHUONG)
) ENGINE=InnoDB;

CREATE TABLE NHANKHAU (
    MANHANKHAU INT AUTO_INCREMENT PRIMARY KEY,
    SOHOKHAU INT,
    HOTEN VARCHAR(100),
    GIOITINH VARCHAR(10),
    NGAYSINH DATETIME,
    NGHENGHIEP VARCHAR(100),
    QUANHEVOICHUHO VARCHAR(50),
    TRANGTHAI VARCHAR(50) DEFAULT 'Thuong tru',
    CMND VARCHAR(20),
    NOITHUONGTRUCHUYENDEN VARCHAR(200),
    NGAYCHUYENDI DATETIME NULL,
    NOICHUYEN VARCHAR(200),
    GHICHU TEXT,
    CONSTRAINT FK_NHANKHAU_HOKHAU FOREIGN KEY (SOHOKHAU) REFERENCES HOKHAU(SOHOKHAU)
) ENGINE=InnoDB;

-- Liên lạc
CREATE TABLE ContactInfo (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    MaNhanKhau INT,
    Type VARCHAR(20),
    Value VARCHAR(255),
    IsPrimary TINYINT(1) DEFAULT 0,
    CONSTRAINT FK_CONTACTINFO_NHANKHAU FOREIGN KEY (MaNhanKhau) REFERENCES NHANKHAU(MANHANKHAU)
) ENGINE=InnoDB;

CREATE INDEX idx_contact_nhankhau_type ON ContactInfo (MaNhanKhau, Type);
CREATE INDEX idx_contact_primary ON ContactInfo (MaNhanKhau, IsPrimary);

-- Biến động nhân khẩu
CREATE TABLE BIENDONGNHANKHAU (
    MABIENDONG INT AUTO_INCREMENT PRIMARY KEY,
    MANHANKHAU INT,
    LOAIBIENDONG VARCHAR(50),
    NGAYBATDAU DATETIME,
    NGAYKETTHUC DATETIME,
    LYDODOICHUYENDI TEXT,
    CONSTRAINT FK_BIENDONGNHANKHAU_NHANKHAU FOREIGN KEY (MANHANKHAU) REFERENCES NHANKHAU(MANHANKHAU)
) ENGINE=InnoDB;

-- Giấy tờ
CREATE TABLE GIAYTO (
    MAGIAYTO INT AUTO_INCREMENT PRIMARY KEY,
    MANHANKHAU INT,
    LOAIGIAYTO VARCHAR(50),
    SOGIAYTO VARCHAR(50),
    NGAYCAP DATETIME,
    NOICAP VARCHAR(100),
    CONSTRAINT FK_GIAYTO_NHANKHAU FOREIGN KEY (MANHANKHAU) REFERENCES NHANKHAU(MANHANKHAU)
) ENGINE=InnoDB;

-- Cán bộ - tài khoản
CREATE TABLE CANBO (
    MACANBO INT AUTO_INCREMENT PRIMARY KEY,
    HOTEN VARCHAR(100),
    CHUCVU VARCHAR(50),
    MAXAPHUONG INT,
    CONSTRAINT FK_CANBO_XAPHUONG FOREIGN KEY (MAXAPHUONG) REFERENCES XAPHUONG(MAXAPHUONG)
) ENGINE=InnoDB;

CREATE TABLE TAIKHOAN (
    MATAIKHOAN INT AUTO_INCREMENT PRIMARY KEY,
    MACANBO INT,
    TENDANGNHAP VARCHAR(50) UNIQUE NOT NULL,
    EMAIL VARCHAR(100) UNIQUE,
    MATKHAU VARCHAR(100) NOT NULL,
    VAITRO VARCHAR(50) NOT NULL,
    TRANGTHAI ENUM('PENDING', 'ACTIVE', 'INACTIVE') DEFAULT 'PENDING',
    CONSTRAINT FK_TAIKHOAN_CANBO
        FOREIGN KEY (MACANBO) REFERENCES CANBO(MACANBO)
) ENGINE=InnoDB;

INSERT INTO TAIKHOAN (MACANBO, TENDANGNHAP, EMAIL, MATKHAU, VAITRO, TRANGTHAI)
VALUES
(1, 'admin01', 'admin01@gmail.com', '123456', 'ADMIN', 'ACTIVE'),

(2, 'canbo01', 'canbo01@gmail.com', '123456', 'CAN_BO', 'ACTIVE'),

(3, 'canbo02', 'canbo02@gmail.com', '123456', 'CAN_BO', 'PENDING'),

(4, 'canbo03', 'canbo03@gmail.com', '123456', 'LANH_DAO', 'ACTIVE'),

(5, 'ketoan01', 'ketoan01@gmail.com', '123456', 'KE_TOAN', 'ACTIVE');

CREATE TABLE LOAIPHI (
    MALOAI INT AUTO_INCREMENT PRIMARY KEY,
    TENLOAIPHI VARCHAR(100) NOT NULL,
    MOTA TEXT,
    BATBUOC TINYINT(1) DEFAULT 0,
    DINHMUC DECIMAL(12,2),
    MUCTIEU DECIMAL(15,2) DEFAULT 0.00 COMMENT 'Tổng số tiền mục tiêu cần đóng góp',
    CONSTRAINT UQ_LOAIPHI_TEN UNIQUE (TENLOAIPHI)
) ENGINE=InnoDB;
CREATE TABLE DOTTHU (
    MADOTTHU INT AUTO_INCREMENT PRIMARY KEY,
    MALOAI INT NOT NULL,
    TENDOTTHU VARCHAR(100) NOT NULL,
    NGAYBATDAU DATETIME,
    NGAYKETTHUC DATETIME,

    CONSTRAINT FK_DOTTHU_LOAIPHI
        FOREIGN KEY (MALOAI)
        REFERENCES LOAIPHI(MALOAI)
        ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE THUPHI (
    MATHUPHI INT AUTO_INCREMENT PRIMARY KEY,
    SOHOKHAU INT NOT NULL,
    MADOTTHU INT NOT NULL,
    SOTIEN DECIMAL(12,2) NOT NULL,
    NGAYDONG DATETIME DEFAULT CURRENT_TIMESTAMP,
    GHICHU TEXT,

    CONSTRAINT FK_THUPHI_HOKHAU
        FOREIGN KEY (SOHOKHAU)
        REFERENCES HOKHAU(SOHOKHAU)
        ON DELETE CASCADE,

    CONSTRAINT FK_THUPHI_DOTTHU
        FOREIGN KEY (MADOTTHU)
        REFERENCES DOTTHU(MADOTTHU)
        ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE INDEX idx_thuphi_ho_dot_loai ON THUPHI (SOHOKHAU, MADOTTHU, MALOAI);

-- Tạm trú - tạm vắng
CREATE TABLE TamTru (
    MaTamTru INT AUTO_INCREMENT PRIMARY KEY,
    MaNhanKhau INT,
    NoiTamTru VARCHAR(100),
    TuNgay DATETIME NOT NULL,
    DenNgay DATETIME NULL,
    LyDo TEXT,
    TrangThai VARCHAR(50) DEFAULT 'Dang tam tru',
    GhiChu TEXT,
    CONSTRAINT FK_TamTru_NhanKhau FOREIGN KEY (MaNhanKhau) REFERENCES NHANKHAU(MANHANKHAU)
) ENGINE=InnoDB;

CREATE INDEX idx_tamtru_nhankhau_ngay ON TamTru (MaNhanKhau, TuNgay);

CREATE TABLE TamVang (
    MaTamVang INT AUTO_INCREMENT PRIMARY KEY,
    MaNhanKhau INT,
    NoiDi VARCHAR(255),
    TuNgay DATETIME NOT NULL,
    DenNgay DATETIME NULL,
    LyDo TEXT,
    TrangThai VARCHAR(50) DEFAULT 'Dang tam vang',
    GhiChu TEXT,
    CONSTRAINT FK_TamVang_NhanKhau FOREIGN KEY (MaNhanKhau) REFERENCES NHANKHAU(MANHANKHAU)
) ENGINE=InnoDB;

CREATE INDEX idx_tamvang_nhankhau_ngay ON TamVang (MaNhanKhau, TuNgay);

-- Lịch sử thay đổi
CREATE TABLE LICHSU_THAYDOI_NHANKHAU (
    MALICHSUTHAYDOI INT AUTO_INCREMENT PRIMARY KEY,
    MANHANKHAU INT NOT NULL,
    LOAITHAYDOI VARCHAR(50) NULL,
    NOIDUNGTHAYDOI TEXT,
    NGAYTHAYDOI DATETIME NOT NULL,
    GHICHU TEXT,
    CONSTRAINT FK_LICHSU_NHANKHAU FOREIGN KEY (MANHANKHAU) REFERENCES NHANKHAU(MANHANKHAU) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE INDEX IX_LICHSU_NHANKHAU_MANHANKHAU ON LICHSU_THAYDOI_NHANKHAU(MANHANKHAU);
CREATE INDEX IX_LICHSU_NHANKHAU_NGAYTHAYDOI ON LICHSU_THAYDOI_NHANKHAU(NGAYTHAYDOI);

CREATE TABLE LICHSU_THAYDOI_HOKHAU (
    MALICHSUTHAYDOI INT AUTO_INCREMENT PRIMARY KEY,
    SOHOKHAU INT NOT NULL,
    NOIDUNGTHAYDOI TEXT,
    NGAYTHAYDOI DATETIME NOT NULL,
    GHICHU TEXT,
    CONSTRAINT FK_LICHSU_HOKHAU FOREIGN KEY (SOHOKHAU) REFERENCES HOKHAU(SOHOKHAU) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE INDEX IX_LICHSU_HOKHAU_SOHOKHAU ON LICHSU_THAYDOI_HOKHAU(SOHOKHAU);
CREATE INDEX IX_LICHSU_HOKHAU_NGAYTHAYDOI ON LICHSU_THAYDOI_HOKHAU(NGAYTHAYDOI);

-- View hỗ trợ
DROP VIEW IF EXISTS VW_NHANKHAU_CHITIET;
CREATE VIEW VW_NHANKHAU_CHITIET AS
SELECT 
    nk.MANHANKHAU,
    nk.HOTEN,
    nk.GIOITINH,
    nk.NGAYSINH,
    nk.NGHENGHIEP,
    nk.QUANHEVOICHUHO,
    nk.TRANGTHAI,
    nk.CMND,
    nk.NOITHUONGTRUCHUYENDEN,
    nk.NGAYCHUYENDI,
    nk.NOICHUYEN,
    nk.GHICHU,
    hk.SOHOKHAU,
    hk.DIACHI,
    hk.NGAYCAP,
    xp.TENXAPHUONG
FROM NHANKHAU nk
INNER JOIN HOKHAU hk ON nk.SOHOKHAU = hk.SOHOKHAU
INNER JOIN XAPHUONG xp ON hk.MAXAPHUONG = xp.MAXAPHUONG;

-- Stored procedures
DELIMITER $$

CREATE PROCEDURE SP_GET_LICHSU_NHANKHAU_BY_HOKHAU(IN SOHOKHAU_PARAM BIGINT)
BEGIN
    SELECT 
        ls.MALICHSUTHAYDOI,
        ls.MANHANKHAU,
        nk.HOTEN,
        ls.LOAITHAYDOI,
        ls.NOIDUNGTHAYDOI,
        ls.NGAYTHAYDOI,
        ls.GHICHU
    FROM LICHSU_THAYDOI_NHANKHAU ls
    INNER JOIN NHANKHAU nk ON ls.MANHANKHAU = nk.MANHANKHAU
    WHERE nk.SOHOKHAU = SOHOKHAU_PARAM
    ORDER BY ls.NGAYTHAYDOI DESC;
END$$

CREATE PROCEDURE SP_THONGKE_GIOITINH()
BEGIN
    SELECT 
        GIOITINH,
        COUNT(*) AS SO_LUONG
    FROM NHANKHAU
    WHERE GIOITINH IS NOT NULL
    GROUP BY GIOITINH;
END$$

DELIMITER ;

